# Site settings
title: Articles of Apathy
# email:
# description: "Yet another blog"
#baseurl: "//articlesofapathy.com"
url: "//articlesofapathy.com"
# twitter_username:
# github_username:

# Build settings
paginate: 5
paginate_path: "/:num/"
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
