# Site settings
title: Articles of Apathy
# email:
description: ""
#baseurl: "//articlesofapathy.com"
url: "//articlesofapathy.com"
# twitter_username:
# github_username:

# Build settings
paginate: 3
paginate_path: "/:num/"
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
